//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperMassive.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SuperMassive.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ArgumentMustNotBeEmpty {
            get {
                return ResourceManager.GetString("ArgumentMustNotBeEmpty", resourceCulture);
            }
        }
        
        public static string ArgumentMustNotBeWhiteSpace {
            get {
                return ResourceManager.GetString("ArgumentMustNotBeWhiteSpace", resourceCulture);
            }
        }
        
        public static string GENERIC_GUARD_FAILURE_ARGUMENT_ISEMPTY_WITHFORMAT {
            get {
                return ResourceManager.GetString("GENERIC_GUARD_FAILURE_ARGUMENT_ISEMPTY_WITHFORMAT", resourceCulture);
            }
        }
        
        public static string GENERIC_GUARD_FAILURE_ARGUMENT_ISNULL_WITHFORMAT {
            get {
                return ResourceManager.GetString("GENERIC_GUARD_FAILURE_ARGUMENT_ISNULL_WITHFORMAT", resourceCulture);
            }
        }
        
        public static string GENERIC_GUARD_FAILURE_ARGUMENT_MUSTBE_GREATERTHAN_WITHFORMAT {
            get {
                return ResourceManager.GetString("GENERIC_GUARD_FAILURE_ARGUMENT_MUSTBE_GREATERTHAN_WITHFORMAT", resourceCulture);
            }
        }
        
        public static string GENERIC_GUARD_FAILURE_ARGUMENT_MUSTNOTBE_NULLOREMPTY {
            get {
                return ResourceManager.GetString("GENERIC_GUARD_FAILURE_ARGUMENT_MUSTNOTBE_NULLOREMPTY", resourceCulture);
            }
        }
        
        public static string GENERIC_GUARD_FAILURE_ARGUMENT_MUSTNOTBE_WHITESPACE {
            get {
                return ResourceManager.GetString("GENERIC_GUARD_FAILURE_ARGUMENT_MUSTNOTBE_WHITESPACE", resourceCulture);
            }
        }
        
        public static string GENERIC_GUARD_FAILURE_INSTANCE_ISNOTOFTYPE_WITHFORMAT {
            get {
                return ResourceManager.GetString("GENERIC_GUARD_FAILURE_INSTANCE_ISNOTOFTYPE_WITHFORMAT", resourceCulture);
            }
        }
        
        public static string GENERIC_GUARD_FAILURE_PRECONDITION_WITHFORMAT {
            get {
                return ResourceManager.GetString("GENERIC_GUARD_FAILURE_PRECONDITION_WITHFORMAT", resourceCulture);
            }
        }
        
        public static string GENERIC_GUARD_FAILURE_TYPE_ISNOTASSIGNABLE_WITHFORMAT {
            get {
                return ResourceManager.GetString("GENERIC_GUARD_FAILURE_TYPE_ISNOTASSIGNABLE_WITHFORMAT", resourceCulture);
            }
        }
        
        public static string GENERIC_GUARD_FAILURE_UNKNOWNTYPE {
            get {
                return ResourceManager.GetString("GENERIC_GUARD_FAILURE_UNKNOWNTYPE", resourceCulture);
            }
        }
        
        public static string GENERIC_GUARD_FAILURE_VALUEPOSITIVE {
            get {
                return ResourceManager.GetString("GENERIC_GUARD_FAILURE_VALUEPOSITIVE", resourceCulture);
            }
        }
        
        public static string GENERIC_GUARD_FAILURE_VALUESTRICTLYPOSITIVE {
            get {
                return ResourceManager.GetString("GENERIC_GUARD_FAILURE_VALUESTRICTLYPOSITIVE", resourceCulture);
            }
        }
        
        public static string IsNotInstanceOfType {
            get {
                return ResourceManager.GetString("IsNotInstanceOfType", resourceCulture);
            }
        }
        
        public static string TypesAreNotAssignable {
            get {
                return ResourceManager.GetString("TypesAreNotAssignable", resourceCulture);
            }
        }
        
        public static string UnknownType {
            get {
                return ResourceManager.GetString("UnknownType", resourceCulture);
            }
        }
        
        public static string Validation_NotValidGuidString {
            get {
                return ResourceManager.GetString("Validation_NotValidGuidString", resourceCulture);
            }
        }
        
        public static string Validation_NotValidSemverString {
            get {
                return ResourceManager.GetString("Validation_NotValidSemverString", resourceCulture);
            }
        }
        
        public static string Validation_NotValidSortedGuid {
            get {
                return ResourceManager.GetString("Validation_NotValidSortedGuid", resourceCulture);
            }
        }
    }
}
