//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperMassive.ExceptionHandling.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuperMassive.ExceptionHandling.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string AddCustomHandlerData {
            get {
                return ResourceManager.GetString("AddCustomHandlerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Type.
        /// </summary>
        internal static string AddExceptionTypeDisplayName {
            get {
                return ResourceManager.GetString("AddExceptionTypeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new exception type that is handled by this exception policy..
        /// </summary>
        internal static string AddExceptionTypeHelpText {
            get {
                return ResourceManager.GetString("AddExceptionTypeHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Info:.
        /// </summary>
        internal static string AdditionalInfo {
            get {
                return ResourceManager.GetString("AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new policy..
        /// </summary>
        internal static string AddPolicyDisplayDescription {
            get {
                return ResourceManager.GetString("AddPolicyDisplayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy.
        /// </summary>
        internal static string AddPolicyDisplayName {
            get {
                return ResourceManager.GetString("AddPolicyDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Handler.
        /// </summary>
        internal static string AddReplaceHandlerData {
            get {
                return ResourceManager.GetString("AddReplaceHandlerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace the exception with another exception..
        /// </summary>
        internal static string AddReplaceHandlerDataDescription {
            get {
                return ResourceManager.GetString("AddReplaceHandlerDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap Handler.
        /// </summary>
        internal static string AddWrapHandlerData {
            get {
                return ResourceManager.GetString("AddWrapHandlerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap the exception within another exception..
        /// </summary>
        internal static string AddWrapHandlerDataDescription {
            get {
                return ResourceManager.GetString("AddWrapHandlerDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        internal static string AttributesDescription {
            get {
                return ResourceManager.GetString("AttributesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        internal static string AttributesDisplayName {
            get {
                return ResourceManager.GetString("AttributesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthorizationProviderTypeDescription.
        /// </summary>
        internal static string AuthorizationProviderTypeDescription {
            get {
                return ResourceManager.GetString("AuthorizationProviderTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterprise Library Exception Handling Application Block.
        /// </summary>
        internal static string BlockName {
            get {
                return ResourceManager.GetString("BlockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot swallow exceptions for methods with non-null return type..
        /// </summary>
        internal static string CantSwallowNonVoidReturnMessage {
            get {
                return ResourceManager.GetString("CantSwallowNonVoidReturnMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HANDLING CHAIN EXCEPTION:.
        /// </summary>
        internal static string ChainException {
            get {
                return ResourceManager.GetString("ChainException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A configuration failure occurred while creating policy ‘{0}’..
        /// </summary>
        internal static string ConfigurationFailureCreatingPolicy {
            get {
                return ResourceManager.GetString("ConfigurationFailureCreatingPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The error occurred while handling an exception for policy &quot;{0}&quot;..
        /// </summary>
        internal static string ErrorHandlingExceptionMessage {
            get {
                return ResourceManager.GetString("ErrorHandlingExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event id.
        /// </summary>
        internal static string EventIdDisplayName {
            get {
                return ResourceManager.GetString("EventIdDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptions Handled/sec is the rate at which exceptions were handled..
        /// </summary>
        internal static string ExceptionHandledHelpResource {
            get {
                return ResourceManager.GetString("ExceptionHandledHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Handlers Executed/sec is the rate at which exception handlers were executed..
        /// </summary>
        internal static string ExceptionHandlerExecutedHelpResource {
            get {
                return ResourceManager.GetString("ExceptionHandlerExecutedHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handlers.
        /// </summary>
        internal static string ExceptionHandlersDisplayName {
            get {
                return ResourceManager.GetString("ExceptionHandlersDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Handler Type.
        /// </summary>
        internal static string ExceptionHandlerTypeDescription {
            get {
                return ResourceManager.GetString("ExceptionHandlerTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Handler Type.
        /// </summary>
        internal static string ExceptionHandlerTypeDisplayName {
            get {
                return ResourceManager.GetString("ExceptionHandlerTypeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception message.
        /// </summary>
        internal static string ExceptionMessageDisplayName {
            get {
                return ResourceManager.GetString("ExceptionMessageDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception message resource name.
        /// </summary>
        internal static string ExceptionMessageResourceNameDisplayName {
            get {
                return ResourceManager.GetString("ExceptionMessageResourceNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception message resource type.
        /// </summary>
        internal static string ExceptionMessageResourceTypeDisplayName {
            get {
                return ResourceManager.GetString("ExceptionMessageResourceTypeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to rethrow exception: The exception to throw is null..
        /// </summary>
        internal static string ExceptionNullException {
            get {
                return ResourceManager.GetString("ExceptionNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies.
        /// </summary>
        internal static string ExceptionPoliciesDisplayName {
            get {
                return ResourceManager.GetString("ExceptionPoliciesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The policy with name &apos;{0}&apos; cannot be found. Exception handling aborted..
        /// </summary>
        internal static string ExceptionPolicyNotFound {
            get {
                return ResourceManager.GetString("ExceptionPolicyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value can not be an empty string or null..
        /// </summary>
        internal static string ExceptionStringNullOrEmpty {
            get {
                return ResourceManager.GetString("ExceptionStringNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type must be of type Exception..
        /// </summary>
        internal static string ExceptionTypeNotException {
            get {
                return ResourceManager.GetString("ExceptionTypeNotException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Types.
        /// </summary>
        internal static string ExceptionTypesDisplayName {
            get {
                return ResourceManager.GetString("ExceptionTypesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception of type &apos;{0}&apos; occurred and was caught..
        /// </summary>
        internal static string ExceptionWasCaught {
            get {
                return ResourceManager.GetString("ExceptionWasCaught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access failed.
        /// </summary>
        internal static string FieldAccessFailed {
            get {
                return ResourceManager.GetString("FieldAccessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatter type name.
        /// </summary>
        internal static string FormatterTypeNameDisplayName {
            get {
                return ResourceManager.GetString("FormatterTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help link : {0}.
        /// </summary>
        internal static string HelpLink {
            get {
                return ResourceManager.GetString("HelpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner Exception.
        /// </summary>
        internal static string InnerException {
            get {
                return ResourceManager.GetString("InnerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log category.
        /// </summary>
        internal static string LogCategoryDisplayName {
            get {
                return ResourceManager.GetString("LogCategoryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message : {0}.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameDisplayName {
            get {
                return ResourceManager.GetString("NameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFFENDING EXCEPTION:.
        /// </summary>
        internal static string OffendingException {
            get {
                return ResourceManager.GetString("OffendingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORIGINAL EXCEPTION:.
        /// </summary>
        internal static string OriginalException {
            get {
                return ResourceManager.GetString("OriginalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Denied.
        /// </summary>
        internal static string PermissionDenied {
            get {
                return ResourceManager.GetString("PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POLICY NAME: {0}.
        /// </summary>
        internal static string PolicyName {
            get {
                return ResourceManager.GetString("PolicyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post handling action.
        /// </summary>
        internal static string PostHandlingActionDisplayName {
            get {
                return ResourceManager.GetString("PostHandlingActionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string PriorityDisplayName {
            get {
                return ResourceManager.GetString("PriorityDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access failed.
        /// </summary>
        internal static string PropertyAccessFailed {
            get {
                return ResourceManager.GetString("PropertyAccessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace exception type .
        /// </summary>
        internal static string ReplaceExceptionTypeNameDisplayName {
            get {
                return ResourceManager.GetString("ReplaceExceptionTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Handling Settings.
        /// </summary>
        internal static string SectionDisplayName {
            get {
                return ResourceManager.GetString("SectionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity.
        /// </summary>
        internal static string SeverityDisplayName {
            get {
                return ResourceManager.GetString("SeverityDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source : {0}.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Trace.
        /// </summary>
        internal static string StackTrace {
            get {
                return ResourceManager.GetString("StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stack trace is unavailable..
        /// </summary>
        internal static string StackTraceUnavailable {
            get {
                return ResourceManager.GetString("StackTraceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string TitleDisplayName {
            get {
                return ResourceManager.GetString("TitleDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Exceptions Handlers Executed is the total number which exception handlers were executed..
        /// </summary>
        internal static string TotalExceptionHandlersExecutedHelpResource {
            get {
                return ResourceManager.GetString("TotalExceptionHandlersExecutedHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Exceptions Handled is the total number of exceptions handled..
        /// </summary>
        internal static string TotalExceptionsHandledHelpResource {
            get {
                return ResourceManager.GetString("TotalExceptionsHandledHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name.
        /// </summary>
        internal static string TypeNameDisplayName {
            get {
                return ResourceManager.GetString("TypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type : {0}.
        /// </summary>
        internal static string TypeString {
            get {
                return ResourceManager.GetString("TypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to handle exception: &apos;{0}&apos;..
        /// </summary>
        internal static string UnableToHandleException {
            get {
                return ResourceManager.GetString("UnableToHandleException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;undefined value&gt;.
        /// </summary>
        internal static string UndefinedValue {
            get {
                return ResourceManager.GetString("UndefinedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use default logger.
        /// </summary>
        internal static string UseDefaultLoggerDisplayName {
            get {
                return ResourceManager.GetString("UseDefaultLoggerDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap exception type.
        /// </summary>
        internal static string WrapExceptionTypeNameDisplayName {
            get {
                return ResourceManager.GetString("WrapExceptionTypeNameDisplayName", resourceCulture);
            }
        }
    }
}
