//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperMassive.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuperMassive.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided string argument must not be empty..
        /// </summary>
        public static string ArgumentMustNotBeEmpty {
            get {
                return ResourceManager.GetString("ArgumentMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided string argument contains only whitespace..
        /// </summary>
        public static string ArgumentMustNotBeWhiteSpace {
            get {
                return ResourceManager.GetString("ArgumentMustNotBeWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument `{0}` is empty.
        /// </summary>
        public static string GENERIC_GUARD_FAILURE_ARGUMENT_ISEMPTY_WITHFORMAT {
            get {
                return ResourceManager.GetString("GENERIC_GUARD_FAILURE_ARGUMENT_ISEMPTY_WITHFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument `{0}` is null.
        /// </summary>
        public static string GENERIC_GUARD_FAILURE_ARGUMENT_ISNULL_WITHFORMAT {
            get {
                return ResourceManager.GetString("GENERIC_GUARD_FAILURE_ARGUMENT_ISNULL_WITHFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument `{0}` must be greater than argument `{1}`.
        /// </summary>
        public static string GENERIC_GUARD_FAILURE_ARGUMENT_MUSTBE_GREATERTHAN_WITHFORMAT {
            get {
                return ResourceManager.GetString("GENERIC_GUARD_FAILURE_ARGUMENT_MUSTBE_GREATERTHAN_WITHFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided string argument must not be null or empty.
        /// </summary>
        public static string GENERIC_GUARD_FAILURE_ARGUMENT_MUSTNOTBE_NULLOREMPTY {
            get {
                return ResourceManager.GetString("GENERIC_GUARD_FAILURE_ARGUMENT_MUSTNOTBE_NULLOREMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided string argument must not be contain only whitespace.
        /// </summary>
        public static string GENERIC_GUARD_FAILURE_ARGUMENT_MUSTNOTBE_WHITESPACE {
            get {
                return ResourceManager.GetString("GENERIC_GUARD_FAILURE_ARGUMENT_MUSTNOTBE_WHITESPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given parameter is not an instance of type `{0}`.
        /// </summary>
        public static string GENERIC_GUARD_FAILURE_INSTANCE_ISNOTOFTYPE_WITHFORMAT {
            get {
                return ResourceManager.GetString("GENERIC_GUARD_FAILURE_INSTANCE_ISNOTOFTYPE_WITHFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precondition `{0}` failed for argument `{1}`.
        /// </summary>
        public static string GENERIC_GUARD_FAILURE_PRECONDITION_WITHFORMAT {
            get {
                return ResourceManager.GetString("GENERIC_GUARD_FAILURE_PRECONDITION_WITHFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type `{1}` cannot be assigned to variables of type `{0}`.
        /// </summary>
        public static string GENERIC_GUARD_FAILURE_TYPE_ISNOTASSIGNABLE_WITHFORMAT {
            get {
                return ResourceManager.GetString("GENERIC_GUARD_FAILURE_TYPE_ISNOTASSIGNABLE_WITHFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown type.
        /// </summary>
        public static string GENERIC_GUARD_FAILURE_UNKNOWNTYPE {
            get {
                return ResourceManager.GetString("GENERIC_GUARD_FAILURE_UNKNOWNTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be positive.
        /// </summary>
        public static string GENERIC_GUARD_FAILURE_VALUEPOSITIVE {
            get {
                return ResourceManager.GetString("GENERIC_GUARD_FAILURE_VALUEPOSITIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be strictly positive.
        /// </summary>
        public static string GENERIC_GUARD_FAILURE_VALUESTRICTLYPOSITIVE {
            get {
                return ResourceManager.GetString("GENERIC_GUARD_FAILURE_VALUESTRICTLYPOSITIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given parameter is not an instance of type {0}..
        /// </summary>
        public static string IsNotInstanceOfType {
            get {
                return ResourceManager.GetString("IsNotInstanceOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {1} cannot be assigned to variables of type {0}..
        /// </summary>
        public static string TypesAreNotAssignable {
            get {
                return ResourceManager.GetString("TypesAreNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;unknown&gt;.
        /// </summary>
        public static string UnknownType {
            get {
                return ResourceManager.GetString("UnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not contain a valid Guid.
        /// </summary>
        public static string Validation_NotValidGuidString {
            get {
                return ResourceManager.GetString("Validation_NotValidGuidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0} does not contain a valid Semantic Versioning value.
        /// </summary>
        public static string Validation_NotValidSemverString {
            get {
                return ResourceManager.GetString("Validation_NotValidSemverString", resourceCulture);
            }
        }
    }
}
